[colors.bright]
black = "#1d2021"
blue = "#458588"
cyan = "#83a598"
green = "#98971a"
magenta = "#b16286"
red = "#cc2418"
white = "#ebdbb2"
yellow = "#d79921"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#1d2021"
blue = "#458588"
cyan = "#83a598"
green = "#98971a"
magenta = "#b16286"
red = "#cc2418"
white = "#ebdbb2"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.padding]
x = 5
y = 5
